package com.mall.vegetable.dao;

import com.mall.vegetable.pojo.VegeDemo;
import java.util.List;

public interface VegeDemoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vegedemo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String vName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vegedemo
     *
     * @mbggenerated
     */
    int insert(VegeDemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vegedemo
     *
     * @mbggenerated
     */
    VegeDemo selectByPrimaryKey(String vName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vegedemo
     *
     * @mbggenerated
     */
    List<VegeDemo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vegedemo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VegeDemo record);
}