package com.mall.vegetable.pojo;

public class VegeDemo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vegedemo.v_name
     *
     * @mbggenerated
     */
    private String vName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vegedemo.nutrition
     *
     * @mbggenerated
     */
    private String nutrition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vegedemo.e_advice
     *
     * @mbggenerated
     */
    private String eAdvice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vegedemo.dish
     *
     * @mbggenerated
     */
    private String dish;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vegedemo.v_name
     *
     * @return the value of vegedemo.v_name
     *
     * @mbggenerated
     */
    public String getvName() {
        return vName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vegedemo.v_name
     *
     * @param vName the value for vegedemo.v_name
     *
     * @mbggenerated
     */
    public void setvName(String vName) {
        this.vName = vName == null ? null : vName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vegedemo.nutrition
     *
     * @return the value of vegedemo.nutrition
     *
     * @mbggenerated
     */
    public String getNutrition() {
        return nutrition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vegedemo.nutrition
     *
     * @param nutrition the value for vegedemo.nutrition
     *
     * @mbggenerated
     */
    public void setNutrition(String nutrition) {
        this.nutrition = nutrition == null ? null : nutrition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vegedemo.e_advice
     *
     * @return the value of vegedemo.e_advice
     *
     * @mbggenerated
     */
    public String geteAdvice() {
        return eAdvice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vegedemo.e_advice
     *
     * @param eAdvice the value for vegedemo.e_advice
     *
     * @mbggenerated
     */
    public void seteAdvice(String eAdvice) {
        this.eAdvice = eAdvice == null ? null : eAdvice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vegedemo.dish
     *
     * @return the value of vegedemo.dish
     *
     * @mbggenerated
     */
    public String getDish() {
        return dish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vegedemo.dish
     *
     * @param dish the value for vegedemo.dish
     *
     * @mbggenerated
     */
    public void setDish(String dish) {
        this.dish = dish == null ? null : dish.trim();
    }
}